# eureka-hello-api env settings
# - default settings used across most projects

#==============================================
# environ
#==============================================
environ:
  LS:
    isRequired: 1
    type: boolean
    defaultValue: 0
    description: '로그 숨김 여부 설정 (0: 해제, 1: 활성화)'
  LC:
    isRequired: 1
    type: boolean
    defaultValue: 1
    description: '로그 컬러링 여부 설정 (0: 해제, 1: 활성화)'
  TS:
    isRequired: 1
    type: boolean
    defaultValue: 1
    description: '로그 타임스탬프 여부 설정 (0: 해제, 1: 활성화)'
  NAME:
    isRequired: 1
    type: string
    defaultValue: none
    description: '프로젝트 프로필 이름 - 예: none'
  STAGE:
    isRequired: 1
    type: string
    options:
      - dev
      - production
    defaultValue: dev
    description: '배포 단계'
  MY_DYNAMO_TABLE:
    isRequired: 0
    type: string
    description: '연동에 사용할 DynamoDB 테이블 이름'
  SQS_ENDPOINT:
    isRequired: 0
    type: string
    description: '연동할 SQS 엔드포인트 또는 설정'

#==============================================
# config
#==============================================
config:
  name:
    isRequired: 1
    type: string
    defaultValue: none
    description: '프로젝트 식별용 이름'
  runtime:
    isRequired: 1
    type: string
    options:
      - nodejs18.x
      - nodejs22.x
    defaultValue: nodejs18.x
    description: '실행 환경'
  region:
    isRequired: 1
    type: string
    defaultValue: ap-northeast-2
    description: 'AWS 리전'
  env:
    isRequired: 1
    type: string
    defaultValue: ${NAME}.yml
    description: 'env 파일 이름'